### ISSUE TITLE
How should one restore the original colorscheme?

### ISSUE THREAD

**Issue by CaledoniaProject** [eugeneching/ida-consonance#1]
Hi Eugene 

I wonder if it's possible to revoke the changes?

**Comment by ghost** [comment]
If you applied the registry file, and didn't make a backup of the IDA registry keys earlier, I'm afraid there's no way to undo the changes, as IDA stores the colors directly in the registry. Also, the consonance color scheme only overwrites one of the color schemes in the registry (there are 4). So if you want the old colors, an easy way (which is _not_ undoing the changes) is to use one of the other color schemes. For instance, perhaps you could switch back to the third color scheme (Palette 3)?

If all fails, and if you need the original IDA registry keys, you could also leave me a note and I can pass them to you.

**Comment by CaledoniaProject** [comment]
Oh Okay Thanks
